name: traccar_client
description: "Traccar Client"
publish_to: 'none'
version: 9.6.5+113

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_background_geolocation: ^4.18.2
  shared_preferences: ^2.5.4
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  firebase_analytics: ^12.0.4
  firebase_crashlytics: ^5.0.5
  quick_actions: ^1.1.0
  rate_my_app: ^2.3.2
  shared_preferences_android: ^2.4.18
  wakelock_partial_android: ^1.0.1
  mobile_scanner: ^7.1.3
  flutter_secure_storage: ^10.0.0
  app_links: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true
