name: traccar_client
description: "Traccar Client"
publish_to: 'none'
version: 9.0.1+93

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_background_geolocation: ^4.16.9
  shared_preferences: ^2.5.3
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  firebase_analytics: ^11.4.5
  firebase_crashlytics: ^4.3.5
  quick_actions: ^1.1.0
  rate_my_app: ^2.3.1
  shared_preferences_android: ^2.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
